---
title: "Project_Milestone_01"
format: pdf
editor: visual
---

## Project Milestone #1

### [Project option selection]{.underline}

Scenario 1: Flu outbreak (simulated) and vaccine uptake in California

### [Create git repository]{.underline}

#### *Share a link to your group's git repository*

https://github.com/shirley-sui/PHW251-Group8-Project.git

### [Roles and responsibilities]{.underline}

#### *Team's preferred communication method*

The team prefers Whatsapp messaging and Zoom meetings to complete project milestones. We have each other emails and phone numbers added to Whatsapps for quicker communication.

#### *Team's preferred meeting times and frequency*

-   When will your team be holding meetings? How frequently will you meet? Are there times or days that work well for everyone? The team will hold meetings once a week, and will cancel any unecessary meeting. Friday afternoon \~4:30 pm.
-   Discuss future non-academic commitments that might affect members' availability. Shirley travels Oct. 5- 8; Nicole travels Nov. 29 - Dec. 3; Kim birthday plans Nov. 23 - 28
-   Discuss meeting tempo: "checking in" at the beginning of meetings versus "just sticking to business". Mixed style between team members checking-in and business. Checking-in will include team progress, effort and any struggle for each team members. We will have agenda items.

#### *Team's preferred method for tracking progress*

-   How is your team going to keep track of progress? Who will be taking minutes, creating agendas, and contacting the course facilitators with questions? We will create a google doc to track progress & assign weekly tasks to each team members. We will take turns each week on who is in charge of taking minutes, creating agendas, and contacting the course facilitators with questions.

-   We encourage you to discuss potential dates and times to meet with a course facilitator during Weeks 3-5. Decide on the best date and time for all. If needed we can take turns going to office hours or going together for specific questions or set-up a one-to-one appointment.

#### *Point person for contacting course facilitators with questions*

For the next milestone assignment we will be assigning: Ngan Nguyen
